# Generated by Django 4.2.5 on 2023-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='email',
        ),
        migrations.AddField(
            model_name='cinema',
            name='inn',
            field=models.CharField(default=1313, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='latitude',
            field=models.CharField(default=1313, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='legal_entity',
            field=models.CharField(default=1313, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='longitude',
            field=models.CharField(default=1313, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='street',
            field=models.CharField(default=1313, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
